
#application.yml \u914D\u7F6E\u5982\u4E0B\uFF1A
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/socks?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456

server:
  port: 8084

mybatis:
  configuration:
    #\u914D\u7F6E\u9879\uFF1A\u5F00\u542F\u4E0B\u5212\u7EBF\u5230\u9A7C\u5CF0\u7684\u81EA\u52A8\u8F6C\u6362. \u4F5C\u7528\uFF1A\u5C06\u6570\u636E\u5E93\u5B57\u6BB5\u6839\u636E\u9A7C\u5CF0\u89C4\u5219\u81EA\u52A8\u6CE8\u5165\u5230\u5BF9\u8C61\u5C5E\u6027\u3002
    map-underscore-to-camel-case: true

logging:
  level:
    #\u6253\u5370SQL\u4FE1\u606F
    com.wsc.mapper: debug